### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by helloxz** [yxw21/chatgpt#1]
Based on the example you provided, the following error occurred:

> NewSessionWithCredential not declared by package chatgptcompiler[UndeclaredImportedName](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#UndeclaredImportedName)

**Comment by helloxz** [comment]
This is my code:

```golang
package controller

import (
	"fmt"

	"github.com/gin-gonic/gin"
	"github.com/yxw21/chatgpt"
)

func NewChat(c *gin.Context) {
	chat := chatgpt.NewChat(chatgpt.NewSessionWithCredential("xxx", "xxx", "xxx").AutoRefresh())
	res, err := chat.Send("hi")
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(res.Message.Content.Parts)
}
```

**Comment by yxw21** [comment]
The readme was wrong, updated.
