### ISSUE TITLE
get data error: context deadline exceeded

### ISSUE THREAD

**Issue by helloxz** [yxw21/chatgpt#3]
I updated the version to 0.5.2, and an error occurred:

> get data error: context deadline exceeded

**Comment by yxw21** [comment]
Is there a problem with v0.5.1

**Comment by yxw21** [comment]
<img width="613" alt="image" src="https://user-images.githubusercontent.com/16237562/209148124-b5b5babf-93a2-4db9-967c-86dc33bff77a.png">

**Comment by helloxz** [comment]
Wait a minute. I'll test it first.

**Comment by helloxz** [comment]
The same error occurs in my normal code before. It may be that ChatGPT blackened my IP or that ChatGPT upgraded the detection mechanism.

**Comment by helloxz** [comment]
I can't use it normally. Is it still normal? Now always prompt:

```json
{
    "detail": {
        "message": "Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}
```

**Comment by yxw21** [comment]
Yes, I use the latest version and everything works fine, can you re-run

**Comment by helloxz** [comment]
The above error still occurs. I am not sure whether it is caused by IP. I will try to change the IP tomorrow.

**Comment by yxw21** [comment]
According to the returned information, it seems that the accesstoken has expired. 
You can print out the accesstoken to check whether it has expired. or
```
cd session
go test -run TestNewSessionWithCredential
```

**Comment by helloxz** [comment]
Found the reason, it seems that my NopeCHA quota has been used up, I re-subscribed to NopeCHA, this problem no longer occurs. But a new problem arises:

```json
{"detail":"Too many requests in 1 hour. Try again later."}
```

**Comment by yxw21** [comment]
> Found the reason, it seems that my NopeCHA quota has been used up, I re-subscribed to NopeCHA, this problem no longer occurs. But a new problem arises:
> 
> ```json
> {"detail":"Too many requests in 1 hour. Try again later."}
> ```

The problem seems to be a limitation of openai. Even if you use chat.openai.com it will show up occasionally.

**Comment by helloxz** [comment]
> > Found the reason, it seems that my NopeCHA quota has been used up, I re-subscribed to NopeCHA, this problem no longer occurs. But a new problem arises:
> > ```json
> > {"detail":"Too many requests in 1 hour. Try again later."}
> > ```
> 
> The problem seems to be a limitation of openai. Even if you use chat.openai.com it will show up occasionally.

Thank you. It should be the IP. I have replaced an IP, and the situation has improved.

**Comment by yxw21** [comment]
This hint does not need to change the ip. It will be restored after a while. I am not sure exactly what the restrictions are. 
You can search for keywords if you are interested.

**Comment by helloxz** [comment]
> This hint does not need to change the ip. It will be restored after a while. I am not sure exactly what the restrictions are. You can search for keywords if you are interested.

If you don't ask once, you have to wait a minute before you can ask again. It seems that this method is still unstable at present, but thank you for sharing.
