### ISSUE TITLE
Enable Proxies

### ISSUE THREAD

**Issue by aminalipour** [yxw21/chatgpt#6]
Hello
do you have any plan to support proxies? because it say 429 too many reqs once i send second request
thanks

**Comment by yxw21** [comment]
I suggest you first confirm if it is an account problem. I have the same problem with my account logging in from a local browser. If it is an account issue you had to change your account.

**Comment by aminalipour** [comment]
i feel we can bypass it with changing the ip, i already tested, if u add a feature to get  proxies array and use randomly in each request will be great, the node js package of chatgpt has this feature

**Comment by aminalipour** [comment]
`chromedp.ProxyServer()`

**Comment by yxw21** [comment]
Are you sure the proxy can be bypassed? I tried using it on a new ip yesterday and it still prompts me 429, so I logged in in my local browser and found consistent results.

**Comment by aminalipour** [comment]
Yeah i'm sure, proxy is good feature

**Comment by yxw21** [comment]
I'm considering whether cloudflare or chatgpt recognizes tls fingerprints. If the tls fingerprint is added, then the proxy will only introduce other problems.

I gave up using the go client to send chat requests and moved to the browser to avoid tls fingerprinting.

**Comment by aminalipour** [comment]
429 is happening due to chatgpt not cloudflare
something is wrong
i tried with an ip and it didnt give me 429 at all, i sent 20 reqs in 5 mins
but on another ip it gave 429 after a request

**Comment by yxw21** [comment]
I mean I am worried that after adding the proxy, chatgpt will not be able to pass the cloudflare check.

**Comment by aminalipour** [comment]
so what is your idea to bypass the 429?

**Comment by yxw21** [comment]
I will test if adding a proxy will improve it.

**Comment by aminalipour** [comment]
thanks, may i did and send a pull request

**Comment by yxw21** [comment]
yes

**Comment by yxw21** [comment]
```
chromedpundetected.WithChromeFlags(chromedp.Flag("proxy-server", "213.171.63.210:41890"))
```
Even adding a proxy still does not avoid this problem.
I think the cause of 429 could be an ip issue or an account issue. If it is an ip issue you are advised to change the server ip or deploy the application to a new server. If it is an account issue, you can register a new account.
<img width="695" alt="image" src="https://user-images.githubusercontent.com/16237562/209494406-ed2892cc-e417-4892-a534-b9abdd1869bd.png">

**Comment by yxw21** [comment]
I got the correct response after trying to change the proxy, so I will add the proxy.

**Comment by aminalipour** [comment]
i suggest to use this code for enable proxy
`chromedp.ProxyServer(browserOptions.Proxy)`
because `flags = append(flags, chromedp.Flag("proxy-server", browserOptions.Proxy))` not working well for all proxy (https, ...)

**Comment by yxw21** [comment]
```
// ProxyServer is the command line option to set the outbound proxy server.
func ProxyServer(proxy string) ExecAllocatorOption {
	return Flag("proxy-server", proxy)
}
```
